# fly.toml app configuration file generated for cmi-with-xai-delicate-sun-4817 on 2025-08-29T04:40:56+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cmi-with-xai-delicate-sun-4817'
primary_region = 'sea'

[build]
  dockerfile = 'Dockerfile'

[env]
  ONNX_MODEL_PATH = '/app/onnx_models/final_model_augv2_89/model.onnx'
  PORT = '8080'
  PYTORCH_MODEL_PATH = '/app/models/final_model_augv2_89'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'performance'
  cpus = 1
