# fly.toml app configuration file generated for cmi-with-xai on 2025-08-29T02:51:00+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cmi-with-xai'
primary_region = 'sea'

[build]


[env]
  PORT = '8000'
  ONNX_MODEL_PATH="/app/onnx_models/final_model_augv2_89/model.onnx" 
  PYTORCH_MODEL_PATH="/app/backend/model/final_model_augv2_89"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'performance'
  cpus = 1
