# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group   
    steps:
      # Checkout code and fetch full LFS files
      - uses: actions/checkout@v4
        with:
          lfs: true  

      # Setup flyctl
      - uses: superfly/flyctl-actions/setup-flyctl@master

      # Deploy using Fly.io
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
